services:

  database:
    image:  mysql/mysql-server:5.6
    container_name: dndwebapp-db
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: dndwebapp
      MYSQL_USER: dndwebapp
      MYSQL_PASSWORD: dndwebapp
      MYSQL_ROOT_PASSWORD: dndwebapp
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: 3308
    expose:
      - "3308"
    ports:
      - 3308:3308


  minio:
    image: minio/minio
    container_name: dndwebapp-minio
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: dndwebapp
      MINIO_ROOT_PASSWORD: dndwebapp
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  minio_storage: {}